"""create_notepad_model

Revision ID: 46af007713a8
Revises: 001
Create Date: 2026-09-21 05:36:40.120321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46af007713a8'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notepad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notepad')
    # ### end Alembic commands ###
