name: Deploy to Render

on:
  push:
    tags:
      - 'v*'

jobs:
deploy:
    runs-on: ubuntu-24.04

    steps:
    - name: Trigger Render deploy
      run: curl -fsS "${{ secrets.RENDER_DEPLOY_HOOK }}&ref=${{ github.sha }}"